# -*- coding: utf-8 -*-
"""AREAYPERIMETRO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o545cfi_Yrx9AvY6u88qOGh95JNB0miE
"""

import math

def cuadrado(lado):
    area = lado * lado
    perimetro = 4 * lado
    return area, perimetro

def rectangulo(base, altura):
    area = base * altura
    perimetro = 2 * (base + altura)
    return area, perimetro

def circulo(radio):
    area = math.pi * radio * radio
    perimetro = 2 * math.pi * radio
    return area, perimetro

def mostrar_menu():
    print("\nElija una figura:")
    print("1. Cuadrado")
    print("2. Rectángulo")
    print("3. Círculo")
    print("4. Salir")
    opcion = int(input("Ingrese su opción: "))
    return opcion

def main():
    while True:
        opcion = mostrar_menu()

        if opcion == 1:
            lado = float(input("Ingrese el lado del cuadrado: "))
            area, perimetro = cuadrado(lado)
            print(f"Área: {area:.2f} Perímetro: {perimetro:.2f}")

        elif opcion == 2:
            base = float(input("Ingrese la base del rectángulo: "))
            altura = float(input("Ingrese la altura del rectángulo: "))
            area, perimetro = rectangulo(base, altura)
            print(f"Área: {area:.2f} Perímetro: {perimetro:.2f}")

        elif opcion == 3:
            radio = float(input("Ingrese el radio del círculo: "))
            area, perimetro = circulo(radio)
            print(f"Área: {area:.2f} Perímetro: {perimetro:.2f}")

        elif opcion == 4:
            print("Saliendo...")
            break

        else:
            print("Opción no válida. Intente de nuevo.")

if __name__ == "__main__":
    main()