# -*- coding: utf-8 -*-
"""MONTOFINALAPAGAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5-hA5Rk3UvAANfOs7FP5wo9iWPuO1L0
"""

# Digite la cantidad de productos
P = int(input("Ingrese el número de productos: "))
subtotal = 0

# Ingrese el precio de los productos a comprar
for x in range(1, P + 1):
    precio = float(input(f"Ingrese el precio del producto {x}: "))
    subtotal += precio

# Hallar IGV y total
IGV = subtotal * 0.18
total = subtotal + IGV

# Resulatados a pagar
print(f"Subtotal: {subtotal}")
print(f"IGV (18%): {IGV}")
print(f"Total a pagar: {total}")