# -*- coding: utf-8 -*-
"""ESTADOACADEMICO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXUcBQZtOsuDWa82DR_uEZOOxV-ZHoFf
"""

while True:
    # Colocar el nombre del estudiante
    nombre = input("Ingrese el nombre del estudiante (o FIN para terminar): ")

    if nombre.upper() == "FIN":
        break

    # Colocar las notas
    nota1 = float(input("Ingrese la primera nota del estudiante: "))
    nota2 = float(input("Ingrese la segunda nota del estudiante: "))
    nota3 = float(input("Ingrese la tercera nota del estudiante: "))

    # Calcular el promedio
    promedio = (nota1 + nota2 + nota3) / 3

    # Definir el estado académico
    if promedio >= 15:
        estado = "Aprobado"
    elif promedio >= 11:
        estado = "Recuperación"
    else:
        estado = "Desaprobado"

    # Mensaje final
    print(f"Hola {nombre}, tu estado es: {estado}")